### ISSUE TITLE
Setup function

### ISSUE THREAD

**Issue by theduke** [lettier/webviewhs#1]
Hey, thanks for the great bindings, they work well and the extensive examples are much appreciated!

I have one API suggestion: `withWindowLoop` could take an additional argument - a setup function that is run once after the window is set up.

Right now I have to run the loop manually , even though `withWindowLoop` would be perfect for me otherwise.

**Comment by lettier** [comment]
Hello @theduke 

I will try to implement this for the next release.

:+1:

**Comment by lettier** [comment]
Hello @theduke 

I have added a setup function to [withWindowLoop](https://lettier.github.io/webviewhs/Graphics-UI-Webviewhs.html#v:withWindowLoop).

Here is an [example](https://github.com/lettier/webviewhs/blob/21f8ac8ff54369ebce1f7600dc71be6ee84ea099/examples-light/how-do-i-communicate-with-haskell-from-javascript.hs#L46).

:+1:
