### ISSUE TITLE
More conservative dependencies

### ISSUE THREAD

**Issue by theduke** [lettier/webviewhs#2]
This library comes with a few heavy dependencies, namely Clay, jmacro and text-format-heavy.

While I'm sure they are nice to have for some users, I have no use for them. 

IMO they should not be required, since they can be plugged in without the provided helper functions quite easily.

**Comment by lettier** [comment]
Hello @theduke 

I will try to implement this for the next release.

:+1:

**Comment by lettier** [comment]
Hello @theduke 

I have added a cabal build flag called `light`.

You can use this flag to exclude the need for clay, jmacro, and text-format-heavy.

For more information, click [here](https://github.com/lettier/webviewhs/tree/21f8ac8ff54369ebce1f7600dc71be6ee84ea099#what-if-i-dont-want-clay-jmacro-and-text-format-heavy).

:+1:

**Comment by theduke** [comment]
Awesome, thanks.
