### ISSUE TITLE
Injecting a local html file

### ISSUE THREAD

**Issue by mradke** [lettier/webviewhs#3]
The bindings look really, really great.

Although, I'd like to know, if it's _required_ to provide `WHS.windowParamsUri        = "http://localhost:SOMEPORT"` to the window?
I think it would be much nicer (at least for deployment), if we could simply inject a html file that contains all the required CSS and JS resources inlined.

So is that already possible, or would that be a hard thing to add?

**Comment by lettier** [comment]
Hello @mradke 

You can inline an HTML page.

I've created an [example](https://github.com/lettier/webviewhs/blob/21ddd4b4872b2e7eb50c9735e70cfbdedf2c6c1a/examples/how-do-i-inline-an-html-page-on-start-up.hs#L23) demonstrating the process.

:+1:

**Comment by mradke** [comment]
Hey @lettier 

Thank you! 🎉 That is awesome! 👍
