### ISSUE TITLE
[Question] Any way to hide the terminal?

### ISSUE THREAD

**Issue by emlautarom1** [lettier/webviewhs#6]
After building the examples I found that if I launch any of the resulting executables a terminal is spawn too (this is the behaviour in Windows 10 at least).

I would like to know if there's a way to start the resulting executables without showing the terminal to the end user, even if a third-party library is needed.

![hide](https://user-images.githubusercontent.com/31224949/72377926-21c71400-36ef-11ea-92b7-0764b7a16cfd.png)

**Comment by Leden** [comment]
Same on Windows 7

**Comment by lettier** [comment]
Hello,

Unfortunately, I cannot test this myself but you can try the following experiment.

Add `-optl-mwindows` [here](https://github.com/lettier/webviewhs/blob/master/webviewhs.cabal#L73) and [here](https://github.com/lettier/webviewhs/blob/master/examples/webviewhs-examples.cabal#L30).

Set this [line](https://github.com/lettier/webviewhs/blob/master/examples/how-do-i-create-a-window-and-have-it-run-itself.hs#L23) to `false`.

Now run the following. 

```bash
cd webviewhs\examples\
stack build
stack exec -- how-do-i-create-a-window-and-have-it-run-itself
```
Or run this if using cabal.

```bash
cd webviewhs\examples\
cabal sandbox init
cabal sandbox add-source ..\
cabal --require-sandbox install -j
cabal --require-sandbox exec -- how-do-i-create-a-window-and-have-it-run-itself
```

:+1:

**Comment by emlautarom1** [comment]
Indeed, this works perfectly: no terminal on sight.

Thanks for your help. I'm closing the issue.
